export const QueryKeys = {
  AUTHOR: "author",
  AUTHORS: "authors",
  AUTHORS_BOOK_REF: "authorsBookRef",
  BEST_SELLERS: "bestsellers",
  BOOK: "book",
  BOOK_DETAILS: "bookDetails",
  BOOKS_DOCS_LENGTH: "bookDocsLength",
  BOOK_SEARCH: "bookSearchResults",
  CART: "cart",
  CART_ITEM_LENGTH: "cartItemLength",
  FAVOR_LENGTH: "favorLength",
  FAVOR_SUBSCRIPTION: "favorSubscription",
  MONTHLY_PICKS: "monthlyPicks",
  MONTHLY_PICKS_PREFETCH: "monThlyPicksPrefetch",
  NEW_BOOKS: "newBooks",
  REVIEW_REPLY: "reviewReply",
  REVIEW_TOTAL: "reviewTotal",
  REVIEW_LENGTH: "reviewDocsLength",
  REVIEW: "review",
  REVIEWS: "reviews",
  SEEN_BOOKS: "seenBooks",
  SEEN_BOOK_LAST_ITEM: "seenBookLastItem",
  RECOMMEND_BOOK: "recommendBooks",
  TODAY_BEST: "todayBest",
  TODAY_PICK: "todayPick",
  USER_PICKS: "userPicks",
};
