export const QueryKeys = {
  AUTHOR: "author",
  AUTHORS: "authors",
  AUTHORS_BOOK_REF: "authorsBookRef",
  BOOK: "book",
  BOOK_DETAILS: "bookDetails",
  BOOKS_DOCS_LENGTH: "bookDocsLength",
  BOOK_SEARCH: "bookSearchResults",
  FAVOR_LENGTH: "favorLength",
  FAVOR_SUBSCRIPTION: "favorSubscription",
  REVIEW_TOTAL: "reviewTotal",
  REVIEW_LENGTH: "reviewDocsLength",
  REVIEWS: "reviews",
  RECOMMEND_BOOK: "recommendBooks",
};
