export const QueryKeys = {
  AUTHOR: "author",
  AUTHORS: "authors",
  AUTHORS_BOOK_REF: "authorsBookRef",
  BEST_SELLERS: "bestsellers",
  BOOK: "book",
  BOOK_DETAILS: "bookDetails",
  BOOKS_DOCS_LENGTH: "bookDocsLength",
  BOOK_SEARCH: "bookSearchResults",
  FAVOR_LENGTH: "favorLength",
  FAVOR_SUBSCRIPTION: "favorSubscription",
  MONTHLY_PICKS: "monthlyPicks",
  MONTHLY_PICKS_PREFETCH: "monThlyPicksPrefetch",
  REVIEW_REPLY: "reviewReply",
  REVIEW_TOTAL: "reviewTotal",
  REVIEW_LENGTH: "reviewDocsLength",
  REVIEW: "review",
  REVIEWS: "reviews",
  RECOMMEND_BOOK: "recommendBooks",
  USER_PICKS: "userPicks",
};
